"""empty message

Revision ID: 6066cdb50417
Revises: 
Create Date: 2017-04-17 10:56:27.456349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6066cdb50417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Text(length=1024), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('name', sa.Text(length=4096), nullable=True),
    sa.Column('score', sa.String(length=255), nullable=True),
    sa.Column('class_', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.String(length=200), nullable=True),
    sa.Column('c_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    # ### end Alembic commands ###
