"""empty message

Revision ID: 9065486c097a
Revises: 
Create Date: 2017-03-08 16:17:53.714930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9065486c097a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('identity_role')
    op.drop_table('subject')
    op.drop_table('school')
    op.drop_table('auth_role')
    op.drop_table('teacher')
    op.drop_table('college')
    op.drop_table('teacher_and_student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_and_student',
    sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], [u'teacher.id'], name=u'teacher_and_student_ibfk_2'),
    sa.ForeignKeyConstraint(['teacher_id'], [u'student.id'], name=u'teacher_and_student_ibfk_1'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('college',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('teacher',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('normal_person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('current_person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('left_person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('over_person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('identity_role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auth_role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['auth_role_id'], [u'auth_role.id'], name=u'teacher_ibfk_2'),
    sa.ForeignKeyConstraint(['identity_role_id'], [u'identity_role.id'], name=u'teacher_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_role',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('school',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mm', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('m33', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('subject',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('college_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['college_id'], [u'college.id'], name=u'subject_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('identity_role',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('student',
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra', mysql.TEXT(), nullable=True),
    sa.Column('e_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telphone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
