"""empty message

Revision ID: d4ad43af2169
Revises: e4d06574542b
Create Date: 2017-04-17 17:22:47.924144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ad43af2169'
down_revision = 'e4d06574542b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('semester', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade', 'semester')
    # ### end Alembic commands ###
