"""empty message

Revision ID: e4d06574542b
Revises: 6066cdb50417
Create Date: 2017-04-17 10:57:21.502043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4d06574542b'
down_revision = '6066cdb50417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('college', sa.Text(length=1024), nullable=True))
    op.add_column('grade', sa.Column('detail', sa.Text(length=4096), nullable=True))
    op.add_column('grade', sa.Column('subject', sa.String(length=255), nullable=True))
    op.drop_column('grade', 'c_type')
    op.drop_column('grade', 'name')
    op.drop_column('grade', 'number')
    op.drop_column('grade', 'sex')
    op.drop_column('grade', 'semester')
    op.drop_column('grade', 'score')
    op.drop_column('grade', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('owner', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('grade', sa.Column('score', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('grade', sa.Column('semester', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('grade', sa.Column('sex', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('grade', sa.Column('number', mysql.TEXT(), nullable=True))
    op.add_column('grade', sa.Column('name', mysql.TEXT(), nullable=True))
    op.add_column('grade', sa.Column('c_type', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('grade', 'subject')
    op.drop_column('grade', 'detail')
    op.drop_column('grade', 'college')
    # ### end Alembic commands ###
